In [6]:
import numpy as np

## 1.创建ndarray
直接从其他序列对象进行类型转换；特殊数组

In [36]:
data_array = np.array([1,2,3,4,5,6,7,8,9,10])
data_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
# 二维
data_list = ([1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10])
data_array = np.array(data_list)
data_array

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [25]:
# 查看ndarray的信息
print(data_array.ndim)  #维度
print(data_array.shape) #尺寸
print(data_array.dtype) #元素数据类型

2
(2, 10)
int32


In [34]:
# 创建特殊数组
a = np.zeros(10)
b = np.ones((3,4)) #创建多维数组，需要两层括号
c = np.ones((2,3,3))
print("a =",a)
print("\nb =",b)
print("\nc =",c)

a = [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

b = [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

c = [[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [35]:
x = np.arange(15)
print(x)
for i in np.arange(8):
    print(i)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
0
1
2
3
4
5
6
7


In [38]:
# 知道ndarray中的元素是有类型的即可
arr1 = np.array([1,2,3],dtype=np.float64)
arr2 = np.array([1,2,3],dtype=np.int32)
print(arr1)
print(arr2)

[1. 2. 3.]
[1 2 3]


In [158]:
# 索引与切片
a = np.arange(0,100,8)
print(a)
print(a[9])
print(a[5:-2])

[ 0  8 16 24 32 40 48 56 64 72 80 88 96]
72
[40 48 56 64 72 80]


## 2.数组函数

In [146]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [147]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [149]:
np.mean(arr)

5.0

In [152]:
np.random.rand(3,3)

array([[0.93824031, 0.91668679, 0.71331186],
       [0.59417934, 0.68131361, 0.51702869],
       [0.2341186 , 0.43701095, 0.37144218]])

In [157]:
np.random.randint(8)

0

In [154]:
np.random.randint(0,5,[3,3])

array([[3, 3, 3],
       [0, 2, 0],
       [4, 4, 4]])

## 3.矢量运算
逐元素运算

In [40]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
# 按照元素运算
print(arr+arr,'\n')
print(arr-arr,'\n')
print(arr*arr,'\n')
print(arr/arr,'\n')

[[ 2  4  6]
 [ 8 10 12]] 

[[0 0 0]
 [0 0 0]] 

[[ 1  4  9]
 [16 25 36]] 

[[1. 1. 1.]
 [1. 1. 1.]] 



In [43]:
arr**2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [44]:
arr+arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

广播：不同形状的数组之间的运算方式

In [87]:
arr1 = np.arange(7)
print(arr1)

# 标量10广播到了其他元素上
arr2 = arr*10
print(arr2)

[0 1 2 3 4 5 6]
[ 0 10 20 30 40 50 60]


In [91]:
arr1 = np.arange(7)
arr3 = np.arange(4)

print(arr1)
print(arr3)
arr1 + arr3

[0 1 2 3 4 5 6]
[0 1 2 3]


ValueError: operands could not be broadcast together with shapes (7,) (4,) 

In [79]:
arr1 = np.arange(4).reshape(-1,1)
arr1 = np.tile(arr1,3)
arr1

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [74]:
arr2 = np.arange(1,4)
arr2

array([1, 2, 3])

In [82]:
arr1+arr2

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [85]:
arr1*arr2

array([[0, 0, 0],
       [1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [78]:
arr3 = np.arange(1,5).reshape(-1,1)
arr3

array([[1],
       [2],
       [3],
       [4]])

In [80]:
arr1*arr3

array([[ 0,  0,  0],
       [ 2,  2,  2],
       [ 6,  6,  6],
       [12, 12, 12]])

In [121]:
# 三维数组，在0轴广播
arr1 = np.array([[0,2,4,6],[1,3,5,7]]).T.reshape(1,4,2)
arr1 = np.concatenate((arr1,arr1,arr1),axis=0)
arr1

array([[[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]],

       [[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]],

       [[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]]])

In [125]:
arr2 = np.array([[0,2,4,6,8],[1,3,5,7,9]]).T.reshape(1,-1,2)
arr2

array([[[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]])

In [126]:
arr1+arr2

ValueError: operands could not be broadcast together with shapes (3,4,2) (1,5,2) 